spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  # spring.batch.job.names : Program Arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job만 실행하겠다.
  batch:
    job:
      # job.name이 있으면 job.name값을 할당하고, 없으면 NONE을 할당하겠다.
      # names에 NONE이 할당되면 어떤 배치도 실행하지 않는다. (값이 없을 때 모든 배치가 실행되지 않도록 막는 역할)
      names: ${job.name:NONE}
